name: air_quality_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - lightgbm>=3.3.0
  - xgboost>=1.5.0
  - optuna>=3.0.0
  - imbalanced-learn>=0.8.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - nbformat>=5.1.0
  - tqdm>=4.62.0
  - joblib>=1.1.0
  - python-dateutil>=2.8.0
  - pytz>=2021.1
  - pytest>=6.2.0
  - black>=21.0.0
  - flake8>=4.0.0
  - pip
  - pip:
    - optuna[integration]
